### ISSUE TITLE
HTML Purifier Configuration

### ISSUE THREAD

**Issue by RubieV** [BarrelStrength/Craft-Master#10]
Love to use Craft. In fields it is possible to enable or disable HTML Purifier, yet for general content blocks this feature is missing. I want to add entries to the HTML Purifier whitelist, but there seems to not be a configuration option for that.

**Comment by BenParizek** [comment]
@RubieV This is a repo for a multi-environment configuration. This is probably a question best asked on Craft Slack or Craft Stack Exchange: https://craftcms.com/community
